env:
    credentials: "ENCRYPTED[https://kazusakiii27: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@github.com]"
    rcloneconfig: "ENCRYPTED[!ccbc6baa684ae8eee44e476475251fc63f750d889d1cfa14549649f5f8782c97d2b3e206eab87f0e65cded3653c34b84!]"
    tokentl: "ENCRYPTED[7581098542:AAEdZUtRJBj4b886Y3Rasx3k3etytkwOe9g]"
    idtl: "ENCRYPTED[6756038310]"
    lunch: lunch nad_dandelion-userdebug
    make: mka nad

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "kazusakiii27"
       - git config --global user.email "kazusakiii27@github.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy kazusakiii27:nad/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source"
      - mkdir -p ~/rom
      - cd ~/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/keepQASSA/manifest.git -b Q -g default,-mips,-darwin,-notdefault
      - git clone --depth 1 https://github.com/kazusakiii27/local_manifest.git -b nad10 .repo/local_manifests
#      - sed -i 's|ssh://git@github.com|https://github.com|g' .repo/manifests/snippets/nad.xml
      - repo sync -c -j8 --force-sync --no-clone-bundle --no-tags
#      - sed -i 's| -u||g' vendor/nusantara/config/branding.mk
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="rahmad"
      - export BUILD_HOSTNAME="IDN-Labs"
      - export KBUILD_BUILD_USER="OhMyVenyx"
      - export KBUILD_BUILD_HOST="IDN-Labs"
#      - export WITH_GAPPS=true
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started!"
#      - ./collect.sh
      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/dandelion/ && ls Nusantara*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz venyx:qassa -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"

